---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
  - npm run build -- -prod # build app and prepare dist folder

# deploy master branch to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 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
  keep-history: true
  on:
    branch: main
  local-dir: dist
  verbose: true
